import "./globals.css";
import { geistSans, geistMono } from "@/app/ui/fonts";

export const metadata = {
  title: "Todo List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
